const demonios = 
['Abalam (Abalan): Principe del infierno, poco conocido y perteneciente a la corte y sequito del rey Paymon. Presenta la figura de una mujer coronada de una diadema centelleante de piedras preciosas. Comanda doscientas legiones de angeles rebeldes y de fuerzas infernales No', 
'Abducius: Demonio que desarraigaba arboles enormes y aplastaba a los hombres con ellos.', 
'Abduxuel: Uno de los demonios gobernantes de las mansiones lunares, de acuerdo a la tradicion de Enoch.', 
'Abrahel: Demonio que se dedica a seducir a los pobres de espiritu, especialmente campesinos y gente de escasa instruccion, tomando siempre la apariencia de una bellisima y dispuesta mujer; su fin es reclutar adoradores del Diablo en la Tierra.', 
'Abraxas (Abrasax y Abracax): Dios griego que se cree representaba el Bien y el Mal en una unica entidad.', 
'Abyssus: Su nombre significa ‘desesperado’.', 
'Acatriel: Uno de los tres principes de los buenos demonios (en la cabala hebrea, que admite demonios de dos clases).', 
'Acham: Demonio de orden inferior, que se conjura el dia jueves y al que le gusta el pan.', 
'Aclahayir: Genio y espiritu de la cuarta hora del Nuctemeron.', 
'Adirael : demonio hijo de Belzebub.', 
'Adonis (Adon, Dumuzi y Tammuz) ‘senor’, ‘amo’: Demonio fenicio piromaniaco que preside los incendios.', 
'Adriel: Uno de los demonios de las mansiones de la Luna, de acuerdo con la tradicion enochiana.', 
'Af: Demonio menor en la mitologia hebrea, con cabeza de carnero; es originario de Nubia y Abisinia.', 
'Agagliareth, tambien conocido como Agaliarept y Agliaret: Gran general del infierno, comandante de la segunda legion; posee el poder de descubrir todos los secretos, y domina en Europa y en Asia Menor. Manda sobre Buer, Gusoyn y Botis.', 
'Agares: Gran duque infernal que puede hacer que los fugitivos regresen, causar terremotos y ensenar lenguas, encontrando placer en dar a conocer expresiones inmorales.', 
'Agation, tambien conocido como Agathion o Agazion: Demonio familiar que solo se presenta al mediodia; aparece en forma humana o de animal domestico y, en ocasiones, se deja encerrar en un talisman, botella o circulo magico para mejor servir a quienes lo invocan, pese a que su poder es muy limitado.', 
'Agnan, tambien conocido como Agnian, Ana y Anan: Espiritu malvado de los tupinambas, en Brasil; se le atribuia el poder de sacar a los muertos de la sepultura, si los parientes no dejaban ofrendas. Torturaba a los humanos y se le podia ver en cualquier lugar bajo diferentes formas.', 
'Agramon: Demonio del miedo.', 
'Agrat-Bat-Mahlaht: Demonio de la mitologia hebrea. Era una de las esposas de Satan y la demonio de las prostitutas.', 
'Ahazu, el Aferrador: Demonio babilonico que provocaba las enfermedades; espiritu de la noche.', 
'Ahpuch, tambien conocido como Ah Puch, Yum-Cimil, Mitnal y Hunhau: Demonio maya. Tenebroso dios de la muerte, representado en forma de cadaver parcialmente putrefacto, con el esqueleto y el craneo visibles; en otras ocasiones, se lo ve en forma de hombre con cabeza de buho. Preside el Mitnal (noveno y mas profundo de los mundos inferiores); los mayas creen que viajaba por las casas de las personas enfermas, buscando nuevas victimas.', 
'Akibel, tambien conocido como Akikel: Uno de los 200 angeles que, bajo el mando de Azazel, corrompio y enseno a los humanos los signos de la Cabala.', 
'Al Rinach, tambien conocido como Alrinach, Albinach y Aldinach: Demonio de Occidente (Egipto) que preside las tormentas, los terremotos, las lluvias, las granizadas y los maremotos; a menudo hunde los navios, y se deja ver en figura de mujer.', 
'Alecto: Una de las tres azotantes Furias (Eumenides o Erinias) griegas del Tartaro.', 
'Algol: Demonio de los astrologos arabes.', 
'Allatou: Demonio femenino, esposa de Nergal; tentaba a las personas a realizar actos inmorales.', 
'Alpiel: Demonio de poca categoria, de caracter indolente y bucolico; se especializa en proteger los arboles frutales.', 
'Alricaus: Demonio que se conjura el sabado; es el jefe de guerra que manda sobre 22 legiones de diablos. Ensena logica y psicologia a quienes le sirven.', 
'Aluca, tambien conocida como Alouqua: Demonio femenino; sucubo que actua como un vampiro, agota a los hombres y les lleva al suicidio.', 
'Alukah: Ente infernal de la mitologia hebrea, de origen babilonico. Chupa la sangre de las personas mientras duermen.', 
'Alyssa: Tambien conocida como Alyssa Dei Sanguinum. Es una semidiosa demoniaca creada por el mismo Angel caido Lucifer al buscar concebir con una humana dando origen a este Angel guerrero manipulador de la sangre, protector de los hombres y del linaje de todos aquellos que le rindan culto a su espiritu.', 
'Amane: Uno de los 200 angeles que —bajo el mando de Samyaza— se rebelaron contra Dios al descender a la Tierra y unirse a los hombres y ensenarles las ciencias prohibidas.', 
'Amazarac: Uno de los 200 angeles rebeldes que descendio del Cielo y enseno a los humanos todos los secretos de la hechiceria y los encantamientos.', 
'Amdusias: Duque infernal de imagen humana o de unicornio que, al ser convocado, viene acompanado por un sonido de trompetas. Los arboles se inclinan segun el desee.', 
'Amon, tambien conocido como Ammon: Marques infernal que cuenta las cosas del pasado y del futuro, ademas de reconciliar a los amigos en disputa.', 
'Amoymon, tambien conocido como Amaimon y Amoimon: Rey infernal (uno de los cuatro, en la parte oriental), y principe de la monarquia; se le evoca por la manana, desde las 9 a las 12, y por la tarde de 15 a 18 horas; aparece rodeado de llamas, ensena astrologia y artes liberales, descubre a sus amigos los tesoros guardados por los demonios. Comanda a losangeles caidos y a las Potencias, y ordena 36 legiones; su lugarteniente es Asmoda (o Asmodeo), el primer principe de sus Estados.', 
'Anamelech, tambien conocido como Anamalech: Su nombre significa ‘buen rey’. Es un demonio oscuro, portador de malas noticias; cuando se hace visible, adopta la forma de una perdiz, suele mostrar su presencia arrojando objetos como balines de plata o monedas. Se le puede oir susurrar por las noches las malas nuevas que lleva. Es augurio de castigo divino por ofensas o mentiras para beneficio propio. Era adorado en Sefaraim (Asiria). Algunos estudiosos de demonologia sostienen que este diablo es la Luna, como Adramelek es el Sol.', 
'Anazareth, tambien conocido como Anazarel: Demonio encargado de la custodia de los tesoros subterraneos; junto a Gaziel y Fecor, conmueve los cimientos de las casas, provoca las tempestades, toca las campanas a medianoche, hace aparecer espectros e inspira terrores nocturnos. Su estigma es que no puede conocer el amor.', 
'Andromalius: Conde infernal que puede devolver tanto al ladron como los bienes robados, castigar a los ladrones y otras personas malvadas y descubrir tesoros ocultos.', 
'Aneberg, tambien conocido como Anabergo y Anneberg: Demonio aleman, con aspecto de macho cabrio con cuernos de oro, o bien como un gigantesco caballo con un gran cuello, que vive bajo tierra y carece de todo rasgo amable; es el terror de los mineros, ya que muchos de ellos mueren al contacto con su espantoso aliento.', 
'Anubis: Dios egipcio de la muerte y amo del infierno (V dinastia), hijo de Set y Nephtys, con cabeza de chacal o de gavilan. Patron de los embalsamadores, conducia las almas para ser sentenciadas en juicio respecto de su futuro.', 
'Any: Demonio que preside el infierno.', 
'Aqueronte: Demonio-rio griego de los infiernos. Nadie podia atravesar dos veces el Aqueronte.', 
'Aquiel: Demonio que se evoca los domingos a la medianoche en un lugar desierto, el rito del conjuro debe hacerse con luna nueva o con el cielo tapado con nubarrones, y el cual pide a cambio un pelo de la cabeza.', 
'Arachula: Espiritu maligno del aire.', 
'Araco, tambien conocido como Arakho: Demonio que arrebataba el vino de la inmortalidad y lucha contra el Sol y la Luna.', 
'Ardad: Demonio que conduce a los viajeros extraviados.', 
'Ariel: En la mitologia hebrea, espiritu demoniaco del aire (mas especificamente de los vientos). En el del islamismo, arcangel de Dios, identificado como un hombre con cara de leon.', 
'Arioc: Demonio de la venganza.', 
'Arioch: Uno de los angeles caidos que fue castigado por seguir la rebelion de Satanas.', 
'Ascaroth: Demonio que protege a los espias y los delatores; depende de Nergal.', 
'Ascicikpasa, tambien conocido como Asic-Pacha o Ascik-Pacha: Demonio turco, relacionado con el amor y el erotismo. Favorece las intrigas secretas, facilita los partos y los medios para romper encantamientos.', 
'Asima: Dios macho cabrio de Siria, adorado tambien en Samaria. Demonio que rie cuando hace el mal.', 
'Asmodeo, tambien conocido como Asmodai, Sydonai, Chammadai, Asmodeus y Asmodaeus): Demonio persa de la religion mazdiana (zoroastriana). En el Libro de Tobit, Asmodeo se enamora de Sara, hija de Raquel, y cada vez que aquella contrae matrimonio, mata al marido la noche de bodas. Asi llega a matar a siete hombres, impidiendo que consumen el matrimonio.', 
'Asmoug, tambien conocido como Aschmog: Demonio de Persia, que siembra las disensiones, querellas y pleitos, bajo las ordenes de Ahriman; se representaba como una serpiente infernal con dos patas, que produce todos los animales venenosos.', 
'Astaroth: Duque infernal los principales ayudantes son tres demonios llamados Amon, Pruslas y Barbatos.', 
'Astarte, tambien conocida como Baalit, Astartea, Estarot y Diana: Reina de los espiritus de la muerte y esposa de Astaroth; preside los placeres del amor, su figura tiene cabeza de ternero con cuernos, y una cruz en la mano. Tuvo dos hijos: el Deseo y el Amor.', 
'Ate: Divinidad malefica griega, hija de Zeus y Eris (la discordia); personificaba la venganza, la injusticia, la perversidad, la fatalidad, el mal como condicion humana o el arrebato y el extravio de la irreflexion. Habitaba en el Olimpo, pero fue expulsada por sembrar la discordia; sutil y voladora, no tocaba el suelo, vagando siempre a la altura de las cabezas de los hombres para inspirarles el mal, y su caracter abstracto y vengativo recuerda el de Erinys y Nemesis.', 
'Athatriel: Angel caido, condenado por no estar de acuerdo ni con Dios ni con Luzbel.', 
'Atropos: La mayor de las tres Parcas (o Moiras) griegas, hijas de Zeus y Temis, las cuales regian el destino de los mortales. Atropos se encargaba de cortar el hilo de la vida.', 
'Avang Dhu: Su nombre significa ‘castor negro’. Es un demonio celta, destructor de la obra del demiurgo (Poder creador universal), representado en la forma de un dragon.', 
'Axeriva Issa: Despues de su Hijo¨Mammon¨, Lucifer acogio a una mujer del nuevo siglo, a la cual le otorgo poderes para que infundiera terror al mundo en su forma humana, es un demonio que carga con la responsabilidad de proteger a su padre cuando llegue el dia del juicio final.', 
'Azahel: Demonio atractivo y seductor, que enseno a las mujeres el arte de maquillarse y la cosmetica en general. Fue uno de los angeles que se rebelaron contra Dios, bajo el mando deAzazel y Samyaza. Se dice que esta encadenado sobre piedras puntiagudas en un lugar oscuro del desierto, esperando el Juicio Final.', 
'Azaradel: Uno de los demonios bajo el mando de Samael, Azazel y Samyaza, que ilustro a los seres humanos sobre el conocimiento de la Luna y su influencia sobre la Creacion.', 
'Azazel (‘cabra de emisario’ o ‘chivo expiatorio’): Entidad demoniaca de la mitologia hebrea.', 
'Azebel: Demonio de segundo orden de la mitologia hebrea.', 
'Azhi Dahaka, tambien llamado Azi Dahaka, Azi Dahak, Dahaka y Dahak: Figura demoniaca de la Persia zoroastrica.', 
'Azlat: Demonio de la mitologia hebrea.', 
'Azrael, tambien conocido como Ezrael, Izrail, Izrafil, Abu-Jahia y Abou-Jaria: En el islamismo, el Angel de la muerte; demonio hebreo cuya categoria es de Arcangel. Fue el lugarteniente de Lucifer durante la rebelion; esta cubierto con un millon de velos, es mas grande que los cielos, y el mundo se encuentra en sus manos como un plato, del que puede comer cuanto quiere. Tiene cuatro caras: una adelante, otra arriba de la cabeza, otra detras, y la ultima debajo de los pies, posee cuatro alas y su cuerpo esta cubierto de innumerables ojos: cada vez que cierra uno, muere un ser humano.', 
'Baal, tambien conocido como Beel y Bel: Divinidad (probablemente el sol) de varios pueblos situados en Asia Menor y su influencia: fenicios, caldeos, babilonios, sidonios e israelitas. Tiene el poder de hacer invisible a quienes lo convocan y puede volver a un hombre en un sabio.', 
'Baalcefon, tambien conocido como Baalzephon, Balcefon y Baal-Sefon: Divinidad de origen egipcio. Capitan de las guardias y centinelas del infierno; a posteriori se encargo de la fidelidad de los esclavos.', 
'Baalzebub: Dios fenicio de los oraculos; demonio de segunda categoria.', 
'Baco, tambien conocido como Iacco: Su nombre procede del termino indoeuropeo que origino al sanscrito baksha (‘devorar’); del griego bakchos, por ser el simbolo del fuego que devora los sacrificios. Es el dios grecorromano de la vid, el bano y el vino, identificado con Dionysos, y que presidia sobre todos los arboles frutales. En Roma le estaban igualmente consagrados el toro, el asno, la cabra, la pantera, el lince, el cerdo, el caballo, la liebre, el delfin, el jabali, la zorra, la abeja, la serpiente y el perro; entre los vegetales, se le dedicaban la vina, la hiedra, la encina, el mirto, el pino, el laurel, el granado, la higuera, el rosal, etc. En Demonologia figura como principe de los satiros y los silenos; es alegre y gozador y cuando asume el aspecto humano, uno de sus pies presenta algun defecto, y su pene es sobredimensionado. Suele presidir el Sabbath.', 
'Bacon: Se le conoce como el demonio de los celos; de mal natural y caracter resentido, es el que siembra la discordia entre amantes.', 
'Bafomet (tambien conocido como Baphomet, Bafometo y Baffometo): Su nombre procede de la fusion de dos terminos griegos cuyo significado aproximado es el de ‘bautismo de sabiduria’.', 
'Bahaman: Demonio que apacigua la colera.', 
'Baltazo: Demonio incubo de gran seduccion, solo se sabe de el que posee a las mujeres para tener relaciones sexuales, pues no se le conoce otra ocupacion.', 
'Barbatos: Uno de los tres demonios ayudantes de Astaroth. Es el conde-duque del infierno.', 
'Barbelo: Demonio de gran poderio. Disfruta dominando a los hombres y explota sus debilidades, como la lujuria y los celos.', 
'Barbudo, tambien conocido como Barqu y Barbu: Demonio poseedor del secreto de la piedra filosofal, que se aparece bajo la forma humana, con la cara cubierta por una blanca y descomunal barba.', 
'Barkai: Demonio de jerarquia menor; conoce los secretos de los astros: fue el maestro de los astrologos.', 
'Baron: Su nombre deriva del celta baran o barwn, ‘Senor’). Es un demonio al que se le ofrendaban las manos y los corazones de los ninos sacrificados. Gilles de Rais era un adepto al demonio, del que obtendria la receta para la Piedra Filosofal.', 
'Barrabam, tambien conocido como Barrabas: Demonio de categoria que era frecuente grabar su nombre en anillos magicos y amuletos.', 
'Batscumbasa, tambien conocido como Batscun Bassa y Batscum-Pacha: Demonio turco que se invoca para atraer el buen tiempo o las lluvias; le gusta mucho el pan, que no consigue en el infierno, por lo que hay que ofrecerle buenas cantidades para atraerse su voluntad.', 
'Bayemon: Rey en Occidente, cuyo nombre aparece en ciertos grimorios; tiene poder sobre Passiel y Rosus.', 
'Bebal, tambien conocido como Babeal y Babael: Demonio que ostenta el grado de principe, y se desempena como el guardian de las tumbas.', 
'Bechard: Senor de los vientos y las tempestades; produce la caida del granizo, la lluvia y difumina los truenos, por el poder de un maleficio que contiene sapos machacados entre otros elementos.', 
'Bechet: Demonio del viernes, cuya predileccion son las nueces; es un espiritu nocturno.', 
'Behemot: Demonio de la mitologia hebrea, enemigo de Leviatan que se enfrentaron al principio de los tiempos y han de ser destruidos por Dios antes de que acaben con su Creacion. Tambien se dice que batallaran el dia del Juicio Final.', 
'Bel: Divinidad suprema de la teogonia caldeo-babilonica, transformado en un demonio cuya voz tiene un sonido retumbante muy particular.', 
'Belcebu ‘senor de las moscas’ (Beelzebub, Baal Zebub y Baal Zabut: En la mitologia hebrea se empleo para designar a Satan o a algun demonio menor, de acuerdo a la costumbre de representar como malignas a las deidades ajenas (el dios creador Baal, en este caso).', 
'Belial (Belhor, Baalial, Beliar, Beliall, Beliel): Demonio que estaba constantemente al acecho para apoderarse de las almas de los que practicaban una sexualidad libre, es un poderoso demonio que representa al elemento tierra, complementandose con Satanas, Lucifer y Leviatan.', 
'Belias: Demonio de gran poderio, es el principe de las virtudes.', 
'Belphegor: Demonio que ayuda a la gente a hacer descubrimientos, principalmente en el campo de la ciencia. Es dificil de convocar debido a que su ofrenda de sacrificio es excremento.', 
'Beng, tambien conocido como Bheng: Su nombre deriva del termino indoeuropeo que origino al sanscrito bheka, ‘rana’. Es el demonio de los gitanos, cuyos adeptos son adoradores de las serpientes, teniendo, en general, gran respeto por los reptiles.', 
'Bentameleon: Diablo posesivo, aunque docil y educado, que llego a pedir permiso y ofrecerse para entrar en un cuerpo.', 
'Bohinum: Su nombre deriva del hebreo bohu, ‘desolacion’. En la mitologia hebrea es el demonio del mal. Tambien se conoce asi a un idolo armenio del metal negro, simbolo de la noche.', 
'Braathwaate: Demonio de la ignorancia.', 
'Brifault, tambien conocido como Brifot, Briffaut y Biffant: Demonio de gran poderio, que suele ser participe en actos de posesion; poco conocido, no obstante, jefe de legion.', 
'Brulefer: Demonio al que se invoca cuando se quiere inspirar amor, garantiza el hecho de cualquier aventura erotica.', 
'Bucon: Demonio del odio, de la peor especie, citado en las Claviculas de Salomon.', 
'Budu, tambien conocido como Vudu, Vodu y Voodoo: Dios africano de la hechiceria; idolo de la isla de Ceilan, representado bajo la forma de un gigante. Enseno el arte de su mismo nombre a los grandes hechiceros de las tribus de Ceilan.', 
'Chaigidiei: Archidemonio cabalistico, que se opone a la influencia del mismo Dios.', 
'Chamgaz: Demonio menor de la mitologia hebrea.', 
'Chamuco, tambien conocido como Quigen y Kuijen: Referencia demoniaca burlesca inspirada por las iglesias cristianas evangelicas no catolicas. En America, es el representativo deSatan.', 
'Cheitan: Demonio nacido del humo.', 
'Chiridirilles: Demonio protector de los caminantes, aparece en forma de hombre negro montado a caballo.', 
'Chu-Chiang: Dios infernal del taoismo chino; preside la Segunda Sala de los Horrores.', 
'Cieguecillo: Pequeno diablo que habitaba el fuego como elemento propio; se lo identifica con la salamandra. Nacio de una chispa que volo de la fragua de Vulcano al seno de Prenesta.', 
'Cimejes, tambien conocido como Kimaris, Cimeies y Cimeries: Marques infernal. Es un guerrero grande que monta un caballo negro, y tiene la capacidad de localizar tesoros perdidos u ocultos, de ensenar el trivium y de hacer a un hombre en un guerrero de su propia semejanza.', 
'Cocito: Demonio-rio griego de los infiernos. El Cocito, de aguas cenagosas, estaba formado por las lagrimas de los condenados.', 
'Coep: Nombre con referencia demoniaca a la cruza de varios seres vivos, cabeza de animal salvaje como un lobo, tronco de ser humano y parte baja Patas grandes y negras (como la cola) de un jaguar. Da referencia y encabeza a los demonios latinos.', 
'Conocido como el veneno de Dios, porque es como un angel de la muerte, el cual cumplia con las ejecuciones que Dios le dictaminaba. Creador y padre de los Vampiros (seres demoniacos que beben sangre para tener inmortalidad en la tierra) y Padre y creador de los Licantropos (Hombres mitad animal, normalmente Lobos). Fue el cuarto angel en ser creado por Dios. Ayudaba a Lilith a sobre vivir en la tierra de Nod hasta que se aparto de ella por su maldad (cabe destacar que no fue el el que tenia hijos con ella). Tuvo una relacion muy Estrecha con Iseth (una Mujer Demonio) hasta que se la comio. Actualmente Casado con un ser femenino de procedencia e identidad desconocida.', 
'Dahaka: Demonio persa de la muerte, demonio del engano y la mentira; es descripto con tres cabezas, y con escorpiones y lagartijas cubriendo su cuerpo.', 
'Damballa, tambien conocido como Damballah Wedo: Dios-serpiente de la religion vudu.', 
'Dantalian, tambien conocido como Dantalion: Duque infernal, con figura de hombre con varias caras (de hombres y mujeres), con un libro en su mano derecha. Ensena Artes y Ciencias; tenia el poder de obrar magia sobre el pensamiento de los hombres, y volver lo bueno en malo.', 
'Decarabia: Marques infernal que conoce todas las virtudes de las hierbas y piedras preciosas que existen.', 
'Demogorgon: Genio de la tierra, que era un anciano demacrado, mugriento y cubierto de musgo que vivia en el centro del planeta; era el experto mago que tenia el poder de dominar los fantasmas y los espiritus del aire. Es el sinonimo griego del demonio ‘desconocido de los hombres’.', 
'Drugia, tambien conocida como Druj, Drug y Drauga: Lugarteniente de Ahriman, llamado ‘la Peste’; su toque provocaba toda enfermedad, conocida o no. Demonio de sexo femenino con tres cabezas, tres bocas, seis ojos y mil sentidos.', 
'Dumah: Angel del silencio y de la muerte segun la Cabala; Comandante de los demonios del Gehenna.', 
'Eaco, tambien conocido como Aiacos: Uno de los tres jueces griegos de los infiernos. Se encargaba de juzgar a los europeos.', 
'Eligos, tambien conocido como Abigor y Eligor: Gran duque infernal que descubre lo oculto y conoce el futuro, sabe de guerras y de soldados. Tambien atrae favores de senores, caballeros y otras personas importantes.', 
'Emma-O, tambien conocido como Yemma Ten, Yemma Dai O y Emma: Rey de los infiernos en el budismo japones, encargado de juzgar las almas de los condenados y fijar el castigo a que se hayan hecho acreedores por sus pecados en la Tierra. Posee un rostro torvo, de color rojo, con larguisimos colmillos.', 
'Empusa: Demonio que se manifiesta siempre al mediodia; se lo describe como una joven y bella mujer con su pie izquierdo de bronce, o con forma de casco de asno. Aparecia en Rusia durante las cosechas donde, bajo la apariencia de mujer viuda, fracturaba los miembros de los segadores. Se decia tambien que era una enviada de Hecate y tenia figura espantosa.', 
'Erlik, tambien conocido como Erlik-Khan: Espiritu maligno de Siberia; dios turco-mongol de los muertos. Se le representa con cabeza de toro, o bien cabalgando un toro; otras veces con cara de bufalo, cabeza con cuernos rodeada de llamas, o tambien con dos cabezas y cuatro manos; asimismo se lo ve con un collar de craneos al cuello; en su mano derecha, un cetro rematado con una calavera; en la izquierda, una espada. Se le ofrecen sacrificios para aplacarle; no obstante, no se le tiene demasiado respeto. Las ofrendas son animales de color negro.', 
'Exael: Decimo angel, que enseno a los hombres el arte de fabricar las armas y maquinas de guerra.', 
'Fecor: Uno de los tres demonios encargados de la custodia de los tesoros ocultos.', 
'Filotano, tambien conocido como Philotanus: Demonio de segunda categoria, lugarteniente de Belial, con el que seduce por medio de la sodomia y la pederastia, pero a diferencia de su amo, no participa de estos actos, sino que los favorece. Tiene predileccion por las obras de brujeria, y protege a los hechiceros contra sus perseguidores.', 
'Flegazon (en ingles Phlegathon): Poderoso demonio, jefe del reino del Centro.', 
'Fleuretty: Segun la literatura cristiana teniente general de Belcebu, que dominaria en Africa. Era experto en plantas “venenosas” (psicotropicas). Demonio nocturno, fomentaba el deseo sexual, y causaba guerras siempre entre los hombres.', 
'Floron: Demonio familiar de la orden de los Querubines condenados.', 
'Furcas: Caballero infernal que enseno la piromancia, quiromancia, logica, retorica, astronomia y filosofia. Es descrito como un viejo cruel con barba y cabello largo, que monta un caballo.', 
'Gadrel: Demonio de gran jerarquia segun la mitologia hebrea.', 
'Gamaliel: Archidiablo cabalistico, promotor de la obscenidad.', 
'Gamchicoth: Archidiablo cabalistico, que embrolla y enreda todas las cosas.', 
'Gaziel (Goziel): Demonio custodio de los tesoros subterraneos, que suele trasladar de un sitio cuando estan a punto de ser descubiertos; asusta con fantasmales repiques de campanas, y posee la facultad de revivir a los muertos. Su denomino de compania se llama Almudena , es el rey de la mentira y la fantasia . Se puede convertir en perro , pero se dice que esa es su forma original.', 
'Goab (Goap): Rey del infierno de la parte occidental, que gobierna a los demonios del mediodia. Se evoca de 3.00 a 12.00, y de 21.00 a 24.00.', 
'Gob: Demonio de la tierra, el cual domina tambien las cosas subterraneas, y promueve los hundimientos, los movimientos sismicos, la expansion de los gases asfixiantes y deletereos; da sus propiedades mortales a las substancias venenosas, preside el desarrollo y propagacion de la peste y otras epidemias e interviene en los sucesos desgraciados de la vida humana, fomentando las pasiones de la avaricia, el orgullo y la crueldad. Su pasion es, precisamente, la avaricia.', 
'Golab: Archidiablo cabalistico que provoca los incendios.', 
'Goleo Binban (Beenban): Demonio del desierto. Hostiga a los melancolicos, y se la conoce como “el espiritu de la soledad”.', 
'Gresil: Demonio de la impureza.', 
'Guayota: Demonio de la Mitologia Guanche, que habita en el interior del Teide (Tenerife, Espana).', 
'Guta: Demonio hungaro que golpea a sus victimas hasta la muerte.', 
'Habondia: Demonio de la mayor jerarquia, considerada la reina de las hadas.', 
'Hades: Dios griego del inframundo y de los muertos.', 
'Hael: Diablo poderoso e influyente en el infierno, del cual dependen muchos otros espiritus.', 
'Hallulaya: Demonio babilonico que atormenta a los hombres en los caminos.', 
'Hanna: Nombre de demonio.', 
'Harab Serap: Archidiablo cabalistico, promotor de los fracasos.', 
'Herodias, tambien conocida como Noctiluca: Reina de la noche, que presidia los Aquelarres y exigia el sacrificio de seres humanos; fue adorada en el siglo XII.', 
'Hiranya Kasipu (‘oro-colchon’) y Hiranyaksha (‘oro-ojos’): En el hinduismo, hermanos demonios de forma humana. Para matar a cada uno, el dios Vishnu encarno en dos oportunidades, como Varaha (jabali) y como Narasinja (un ser mitad hombre y mitad leon).', 
'Humtaba: Demonio de origen babilonio, de aspecto horrible, con una boca que vomita llamas y un aliento mortal.', 
'Incubo, tambien conocido como Popo Bawa, Trauco de Chiloe, Liderc y Mara: Demonio masculino medieval que busca, al igual que su version femenina, Sucubo, tener relaciones sexuales con los humanos, en su caso las mujeres. Las victimas viven la experiencia como en un sueno sin poder despertar de este.', 
'Isabo: Demonio inferior, cuya figura esta provista con alas largas y punos robustos.', 
'Ishtar, tambien conocida como Istar, Isthar, Zarpanith, Belit, Attar, Sarpanit, Astarte, Terpanit, Milita y Ashtar: Diosa caldea del amor, adorada tambien en Babilonia y Asiria; se la identificaba con los ritos de fertilidad. Regia la belleza, el amor, la guerra, la victoria, etc. Las religiones posteriores la demonizaron.', 
'isul Iblis (Iblis al-Quadim, Eblis, Al-Harith, Azail, Sheitan, Satan): En el islamismo es un archidemonio y jefe supremo de los demonios yinas (djinns). Se lo asocia al pavo real y, por lo tanto, al dios Melek Tawus. Suele representarsele como un espiritu estupido, adornado con plumas de pavo real y con cabeza de mulo. Iblis es androgino, con un sexo en cada pierna, pudiendo autofecundarse, y como consecuencia, poniendo diez huevos diarios, de los cuales nacen 70 demonios masculinos (shaytan), o femeninos (shaytana). A su lado todo es venenoso. Probablemente el nombre Iblis sea una alteracion fonetica arabe del vocablo griego diavolos, ‘fluye hacia abajo’.', 
'Ivannus: Demonio de nivel superior a medio, su figura es de una prolongada altitud y unos cuernos largos y anchos con dos tatuajes de pentagramas en la espalda, popularmente conocido en el habla hispana y en parte europea como ivann.', 
'Jana: Demonio de gran poder, integrante de los espiritus Divi, junto a Saracil, Sathiel y Amon, entre otros.', 
'Jezbet (Jezebeth, Xezbet, Xerbeth): Demonio de las mentiras y los milagros imaginarios y fraudulentos.', 
'Josefa: Demonio femenino, fue considerada una de los demonios mas poderosos de la existencia por los ideales que tenia. Tomaba forma humana para seducir a todas las personas que quisiera y que no la pudieran olvidar.', 
'Junier: Poderosisimo demonio, principe de los angeles.', 
'Kelby o Kelpy: Espiritu maligno de las aguas, con apariencia de caballo, y que a veces empuna una antorcha.', 
'Kellen, tambien conocido como Kelen: Junto a Nisroc, preside los amores ilicitos, los desordenes y las orgias.', 
'Kelvin: Conocido como anticristo o hades. Su apariencia da a conocer a un buen hombre, empuna una espada la cual es capaz de cortar cualquier objeto o ser, posee la capacidad de revivir cuantas veces quiera sin impedimento alguno. Nace el primero de Diciembre del 2006, tiene una maldicion que data de que su poder sera retenido hasta los 25 anos y segunlas leyendas es capaz de derrotar a El Diablo.', 
'Kerobal, tambien conocido como Turban Querobal: Demonio turco, invocado por las brujas en muchos de sus maleficios.', 
'Kisin: Advocacion de Ah-puch, dios maya de la muerte. Se lo representa descarnado. Es equivalente al Satan de la cultura semitica.', 
'Kobal, tambien conocido como Kabal y Robals: Director general de los teatros del infierno y patron de los comediantes. Es un demonio perfido, que muerde y dana mientras rie.', 
'Kumbhakarna (‘orejas [como] ollas’): En el hinduismo, gigantesco monstruo ceilandes de 420 km de altura, que —segun el capitulo 6 del Ramayana— solo podia estar despierto un dia cada seis meses. Fue matado por el dios Rama.', 
'Labasu: Su nombre significa ‘el que derriba’. Es un demonio babilonico que solia traer la desdicha a los hogares; era identificado como un ladron detestable.', 
'Lagasse: Demonio de la hipocresia.', 
'Lamashtu, tambien conocida como Lamastu y Labartu: Divinidad asirio-babilonica, hija de Anu. Es un demonio de sexo femenino, negro, esteril e insaciable, con figura de monstruo con torso de mujer y cabeza y garras de leon, orejas y dientes de asno, provisto de alas, y en posicion de amamantar a dos cachorros sentado en un asno. Era muy temido por las mujeres parturientas y las madres lactantes. Adopta siete formas diferentes, y es uno de los siete demonios de Babilonia.', 
'Lanithro: Demonio del aire.', 
'Leraje, tambien conocido como Leraie, Leraikha, Leraye, Loray y Oray: Gran marques infernal causante de grandes batallas y disputas. Es descrito como un apuesto arquero vestido de verde que carga un arco.', 
'Leshy, tambien conocido como Ljeschie y Lieschi: Demonio eslavo que nacio de la relacion carnal de un diablo con una mujer. Tiene forma humana, pero con piernas, orejas y cuernos de cabra, semejante a un satiro griego; posee la facultad de adquirir la altura del medio donde se mueve.', 
'Lete, tambien conocido como Leteo: Demonio-rio griego de los infiernos. Sus aguas hacian olvidar todo lo pasado a quienes las bebian.', 
'Leviatan, tambien conocido como Liwyatan: Bestia marina del Antiguo Testamento, a menudo asociada con Satanas. El termino Leviatan ha sido reutilizado en numerosas ocasiones como sinonimo hoy en dia de gran monstruo o criatura.', 
'Licas, tambien conocido como Lycas y Alybas: Demonio del Tamesis (Inglaterra). Era sumamente negro, con cuerpo hediondo y cubierto de una piel de lobo; se le propiciaban sacrificios humanos anuales.', 
'Lilitu, tambien conocido como Lilit y Lilith: Demonio, primera mujer creada (antes que Eva). Uno de los tres demonios de la noche mesopotamicos, junto con Lilu y Ardat Lili. El sexo de Lilit es femenino, es el demonio de rango Principado, encargado de las huestes de sucubos o mujeres-demonio creadas para extraer el semen a sus victimas y procrear demonios por la chispa divina de vida puesta en ello, comanda ese rango de inmundicia para secar a los hombres por medio de suenos humedos, lascivia, sexo ocasional, etc. Todo acto sexual que dependa de inmundicia le rinde tributo a este demonio.', 
'Lilu, tambien conocido como Lilla: Uno de los tres demonios de la noche mesopotamicos, junto con Lilit y Ardat Lili. Es un espiritu errante de sexo masculino, existente en la mitologia acadia. Equivale a la figura del vampiro.', 
'Lucifer, tambien conocido como Luzbel, Heosforo o Hespero: Demonio grecorromano identificado con uno de los angeles caidos. Segun mitos hebreos no biblicos, Lucifer era un querubin que, por soberbia, se rebelo contra Dios y como castigo fue expulsado del cielo por el arcangel Miguel. A pesar de que la mitologia hebrea consideraba a Lucifer y a Satanascomo dos entidades separadas, el cristianismo fundio ambos conceptos para identificarlos, sin mas, con el Diablo.', 
'Lul: Demonio de orden inferior, segun la mitologia hebrea.', 
'Magistelo: Demonio colaborador de brujos, en forma de sucubo o incubo.', 
'Magoa: Potente demonio oriental. Rey de la zona que responde a las preguntas que se le formulan.', 
'Mahonin: Demonio menor, proviene de la tercera jerarquia y la segunda orden de arcangeles; vive en el agua.', 
'Mania, tambien conocida como Muta, Larunda, Lara, Tacita, Locura y Lalaria: Diosa etrusca del infierno; antigua divinidad que se veneraba en las Fiestas Compitales en compania de los Lares; era considerada como la madre o la abuela de los Manes y la diosa del silencio. Se le ofrecian en sacrificio adormideras, perros y victimas humanas ; se la representaba con figura aterradora.', 
'Mantor: Demonio caldeo que personificaba la fiebre.', 
'Mantus: Dios de los etruscos, soberano del mundo infernal; era un ser deforme y espantable, armado con un sable o un mazo, y con alas y corona.', 
'Mastema: Su nombre deriva del hebreo mastim, ‘hostil’. Es el principe y jefe de los espiritus malignos que nacieron de la union entre los angeles caidos y las mujeres.', 
'Mastiphal: Uno de los principes de las tinieblas.', 
'Medusa: Una de las tres Gorgonas de la mitologia griega, las cuales convertian en piedra a todo aquel que las mirase directamente a los ojos. Perseo le corto la cabeza a Medusa.', 
'Mefistofeles, tambien conocido como Mefisto: Principe del infierno, subordinado a Lucifer. En muchas ocasiones tambien se toma como sinonimo del Diablo mismo.', 
'Megera: Una de las tres azotantes Furias (Eumenides o Erinias) griegas del Tartaro.', 
'Melanisalcayuto: Este demonio es un mito en el mundo de los demonios, es muy poderoso.', 
'Melek Tawus, tambien conocido como Melek Taus: Su traduccion literal es ‘angel-pavo real’. Es un demonio mesopotamico, de la religion yazidi, para la que no es considerado demonio, sino el lider de los arcangeles. Tenia forma de pavo real, o de gallo, o bien un hibrido entre los dos.', 
'Merigaz: Demonio menor de la mitologia hebrea.', 
'Merihim: Espiritu infernal, principe del aire y de los demonios de la pestilencia.', 
'Minos: Uno de los tres jueces griegos de los infiernos. Se encargaba de juzgar a aquellos que Eaco y Radamanto no habian sabido juzgar.', 
'Minoson: Demonio sucubo dependiente de Hael; su cometido es hacer ganar en toda clase de juegos.', 
'Morail: Demonio que tiene el poder de hacer invisible a cualquiera.', 
'Munkir, tambien conocido como Munchir: Angel negro musulman, maligno, companero de Nekir, que habitaba el Adhab Algab (purgatorio), y atormentaba a los malvados.', 
'Murmur: Demonio de la musica.', 
'Nabam: Espiritu maligno del sabado, muy irascible, y al cual le complace el pan quemado.', 
'Nayla: tambien conocida como Nahamay Nhama: Sucubo y madre original de los diablos, una de las cuatro segun el Talmud, diablesa de la seduccion, es la hermana de Tubalcain.', 
'Nebiros: el Senor de los muertos: Lider de los nigromantes infernales. Es la mano derecha del angel caido Lucifer, quien le dio el poder sobre toda la milicia infernal, nombrandolo Mariscal de las milicias infernales. Se dice que tiene el poder de ver el futuro y crear el mal sobre quien el quiera. Tambien conoce las propiedades magicas de los metales, vegetales y minerales.', 
'Nejustan: Demonio de orden menor, citado en la Biblia.', 
'Nekir, tambien conocido como Nechir: Angel negro del purgatorio musulman (Adhab Algab/ Adab-el-Kabr), que atormentaba a los malvados, junto a su companero Munkir.', 
'Nembroth, tambien conocido como Mambroth y Naimbroth: Demonio al cual los magos consultan los martes, y al cual, para despedirle, le arrojan una pequena piedra.', 
'Nemesis: Diosa griega de la venganza y de la justicia distributiva.', 
'Nergal, tambien conocido como Nirgal: Dios sumerio-babilonico del inframundo y senor de los muertos, siendo considerado como el aspecto siniestro del dios solar Shamash. Gobierna el inframundo junto a su consorte, Ereshkigal. Nergal es el portador de la pestilencia, la fiebre y la devastacion, y sus atributos son la hoz y la porra.', 
'Nibjan: Demonio de la mitologia hebrea, hallado en pasajes de la Biblia.', 
'Nigrum: Demonio principalmente Europeo, muchas veces mostrado en forma de gato negro o cuervo y muy pocas veces como un hombre con cabeza de ciervo. Engana a los humanos haciendoles creer que tienen poder sobre el, pero al final tomara sus almas para ofrecerselas a Belial. Se dice que desde el siglo X se ha aparecido como un hombre de muy buena', 
'Nina: Diosa babilonica; diablesa con forma de serpiente.', 
'Nisroch: Angel caido del orden de los principados asociado a Belphegor. Tambien se le considera el dios asirio de la agricultura.', 
'Ob: Demonio de los sirios; era ventrilocuo y podia expresarse por cualquier orificio del cuerpo.', 
'Oiellet: Principe de los Dominios; tentaba a los hombres para que rompieran el voto de la pobreza, por lo tanto, es el demonio de la riqueza; es invocado en las letanias del Sabbat. Oilette, Oeillet.', 
'Orthon: Demonio de origen desconocido, que aparece en actos de posesion en Francia, y es adorado por el culto satanico-masonico del Paladinismo (siglo XIX).', 
'Ovahiche: Demonio patrono de los juglares, otorga el don de la rima y la improvisacion y toca y ensena maravillosamente el arte de la guitarra.', 
'Paxhet: Diablesa felina de categoria menor en la religion egipcia.', 
'Pazuzu: Es el rey de los demonios del viento, hijo del dios Hanbi, en la mitologia sumeria, asiria y acadia. Para los sumerios, tambien representaba el viento del suroeste, que traia las tormentas, y tambien el portador de la peste y las plagas, del delirio y de la fiebre.', 
'Peralda: Demonio cuyo dominio es el aire; promueve huracanes, ciclones, se combina con Nicksa para hacer caer lluvias torrenciales, con Gob para difundir las enfermedades infecciosas y hacer inhabitables ciertos lugares, y con Djim para dirigir el rayo hacia los sitios y cosas donde pueda esparcir la destruccion y la muerte; su pasion es la colera. Habita las solitarias cuspides de las montanas orientales al Norte y al Poniente.', 
'Perico: Demonio aleman, comprador de almas; aparece en el lecho de los moribundos en forma de enano.', 
'Phenex (Phenes): Gran Marques infernal que se manifiesta en forma de fenix y tiene veinte legiones de demonios bajo su mando. En el Pseudomonarchia Daemonum se lo describe como un excelente poeta, que ensena todas las artes maravillosas.', 
'Rabisu (‘el que acecha’, vagabundo) o Habisu: Demonio asirio-babilonico, que andaba siempre haciendo apariciones imprevisibles, se escondia en los rincones oscuros y siempre trataba de provocar enredos y trastornos a los habitantes de las casas. Era tan horrible que a los que lo veian se les erizaban los vellos del cuerpo.', 
'Radna: Demonio creado por el odio, vanidad , envidia , lujuria, gula, pereza y avaricia de las personas se decia que era el rey de los demonios, ansioso de sangre, se alimentaba de los corazones de las personas y de cualquier criatura que se metiese en su camino, se dice que era capaz de absorber a sus oponentes y ademas imitar sus apariencias y habilidades.', 
'Rahab: Demonio menor, principe de los oceanos.', 
'Rakuti: Demonio de origen desconocido representado con dos cabezas. Se decia que era el supervisor de la rueda de la fortuna, una especie de ruleta que senala lo aleatorio de la buena o mala suerte. Por ello se le atribuye el poder de controlar el destino.', 
'Ravana: En la mitologia hindu, demonio de diez cabezas y diez pares de brazos. Fue matado por el dios Rama.', 
'Richpe o Rechep: Diablo de jerarquia menor, segun la mitologia hebrea.', 
'Rorxibuz o Rodmentor: Poderoso demonio, principe de las dominaciones; es el diablo del amor.', 
'Sabanahz: Demonio que tienta en los bosques, o en las cercanias.', 
'Sabazios, Sabazis, Sabacio o Sabasius: Demonio frigio, jefe del Sabbat de los brujos; se le representaba con el pene manchado de sangre, cuernos, y su emblema era la serpiente. Su companera era Bendis, o bien Cotys. Se lo identifica con el griego Dionisos y el romano Baco.', 
'Sakar: Genio infernal que —segun el Talmud— yace en el lago de Tiberiada atado con una piedra al cuello, a modo de castigo.', 
'Samael Es el Primer Angel caido, un demonio y uno de los principes del infierno, conocido como la serpiente que engano a Eva para que probara del fruto prohibido', 
'Samamiel: Demonio de alta jerarquia en Constantinopla, cuya preferencia eran las mujeres rubias.', 
'Samyaza (Semiasas): Capitan de los 200 arcangeles rebeldes, junto con Azazel, que es su subordinado inmediato.', 
'Saracil: Uno de los tres demonios, llamados Divi, cuya morada esta cerca de la Luna, y que reinan sobre la tierra y el mar.', 
'Sargatanas: Reviste el grado de brigadier de las milicias del Averno. Tiene el poder sobre la invisibilidad, ensena cada una de las astucias humanas y las ciencias secretas.', 
'Satan (Satanas, contrincante, enemigo)', 
'Sathariel: Archidiablo cabalistico, que entorpece la misericordia divina.', 
'Sathiel (Sariel): Demonio companero de Aamon, y que forma parte de los Divi o seres superiores. Es uno de los principes de la Luna.', 
'Seddim: Demonio de poder destructor.', 
'Sidragaso (Sidragasum): Senor del ducado infernal de Lagneia, al mando de 70 legiones, conformadas por incubos. Tiene rostro de leopardo, torso de hombre, patas de macho cabrio, cola de escorpion y alas de cuervo. Esta envuelto por exquisitas fragancias, que despiertan el apetito sexual en las mujeres, y tiene el don de la palabra galante, mediante la cual envuelve a sus victimas. Es llamado tambien Bitru o Sytry. Tiene por mision seducir a las mujeres, haciendoles creer que son las mas hermosas, e incitarlas a mostrase desnudas en un baile demoniaco durante el Sabbath o al libertinaje y la orgia, con el proposito de exacerbar el deseo carnal en los hombres, procurando que se efectue el acto de la fornicacion entre los dos sexos. Wilfried de Regensburg en Atrium Infernalis in Pandemonium menciona como en 1357 sedujo a una mujer de nombre Sylvia, esposa de Gunther, un modesto comerciante en la ciudad de Augsburgo en el ducado de Baviera, convenciendola a mostrarse desnuda ante un grupo muy nutrido de clientes, con la promesa de que tras esto, ellos comprarian todo lo que su marido quisiera y al precio que este fijara. Silvya, movida por la ambicion, hizo caso a Sidragaso y se exhibio ante ellos, quienes dominados por la lujuria, no solo contemplaron su desnudez, sino copularon con ella. Tras este acto orgiastico, Gunther amaso una fortuna, cumpliendose lo que a Sylvia se le habia prometido. Sin embargo, a los nueve meses ella concibio a un nino por completo deforme y de aspecto repugnante, ademas de que ella murio en el parto. Se piensa que es el principal responsable del crecimiento que ha tenido la pornografia en Europa.', 
'Sira (Seera, Sire): Poderoso principe, bajo el mando de Amaymon, que aparece como un apuesto hombre montado sobre un caballo alado. Controlaba el tiempo, haciendo que fuera mas deprisa o mas despacio, en instantes podia transportar objetos o seres de un lugar a otro.', 
'Sorath: Demonio al mando de lucifer, es aquel que rige las 616 estrellas de la muerte.', 
'Tartac (Tartak): Demonio de la mitologia hebrea, citado en algunos pasajes de la Biblia. En Kutha era el dios del viento, y era adorado por los colonos asirios de Samaria.', 
'Tefnet (Tefnut): Demonio de menor categoria en la mitologia egipcia; diablesa felina con cabeza de leona, hermana y consorte de Shu, y personificacion del elemento humedo; en ella se sintetizaba todo el peligro de la seduccion femenina.', 
'Tetal: Demonio caldeo, cuyo poder residia en tomar posesion y deteriorar manos y brazos de los seres humanos.', 
'Thaumiel: Archidiablo cabalistico, que pretendio ser tanto como Dios.', 
'Tiamat: En Babilonia, princesa de los diablos del Caos y diosa de las aguas saladas. Era representada con garras de ave de rapina y grandes cuernos. Tambien se la representaba con dos cabezas.', 
'Togarini: Archidiablo cabalistico, inspirador de las guerras.', 
'Tuculca (Tuculcha, Tuchulca): Monstruo espantoso de la mitologia etrusca, de origen infernal, provisto de pico de aguila, orejas de asno y serpientes por cabellos, cuerpo humano de color amarillento provisto de alas y patas de pajaro', 
'Ufir (Uphir): Demonio versado en quimica, protector de los curanderos; es tambien el medico del infierno.', 
'Unsere: Archidiablesa de la fertilidad y la brujeria.', 
'Uzza: Angel que —por su lujuria con las mujeres (consecuencia de su endeble espiritu)— fue convertido en demonio.', 
'Verrier: Demonio de la desobediencia, es ademas, versado en herboristeria y todo tipo de plantas en general.', 
'Verrine: Demonio de orden menor, considerado como el diablo de la salud y de la impaciencia.', 
'Volac: Gran Presidente del Infierno, teniendo treinta legiones de demonios bajo su mando.', 
'Vucub Caquix: demonio quiche, aparece en el Popol Vuh como un ser vanidoso y egolatra.', 
'Xaphan: es un demonio que intento quemar el cielo, por esa accion es conciderado como el arquetipo de demonio perdedor', 
'Yakshi: Demonio sucubo hindu, que podia adoptar el aspecto de mujer bella e insaciable.', 
'Yama: Rey del infierno chino Di Yu, un laberinto de mazmorras subterraneas donde las almas son tratadas en concordancia con sus pecados terrenales. Se parece al severo y piadoso semidios hindu Yama, que posee la misma funcion.', 
'Yekum: Uno de los angeles malvados que sedujo a los hijos de los hombres y los angeles que habian descendido del Cielo.', 
'Yoma: es un tipo de demonio parasito nacido del derramamiento de sangre entre shinobis. Si la sangre derramada dentro de una barrera shinobi fluye libremente lo suficiente.', 
'Zabulon: Demonio de la gula, ademas de incubo lascivo e impudico.', 
'Zabulus: Demonio incubo, al que durante el Medioevo se le atribuian hechos de posesion.', 
'Zagan: Demonio rey y presidente del infierno, protector de aquellos que cometen fraude con monedas falsificadas, se le describe como un hombre con cabeza de toro y alas de grifo.', 
'Zauron: Demonio de la religion mazdea, dios del robo y el asesinato. Bajo el poder de Ahriman, tienta a los reyes sugiriendoles la tirania.', 
'Zimiar (Zymyar): Rey del infierno, de la parte septentrional.', 
];
exports.demonios = demonios